### Import numpy as np and see the version

In [3]:
import numpy as np

np.__version__

'1.20.3'

### How to create a 1D array?

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
## create a boolean array?

np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
## Extract all odd numbers from arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr
for i in arr:
    if i%2!=0:
        print(i)

1
3
5
7
9


In [21]:
## Replace all odd numbers in arr with -1 

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2==1]=-1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
a = np.arange(10)
a

print(a.reshape((5,2)))
print(a.reshape((2,5)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
a = np.array([1,2,3])

array([3, 6, 9])

In [32]:
###  common items between two python numpy arrays

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

for i in a:
    if i in  b:
        print(i)
        
np.intersect1d(a,b)

2
2
4
4


array([2, 4])

In [33]:
## From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [34]:
np.setdiff1d(b,a)

array([6, 7, 8, 9])

In [35]:
## Get the positions where elements of a and b match 
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [39]:
## Get all items between 5 and 10 from a

a = np.array([2, 6, 1, 9, 10, 3, 27])

a[np.where((a>=5) & (a<=10))]

array([ 6,  9, 10])