<a href="https://colab.research.google.com/github/rvjh/PythonPractice/blob/main/PythonCoding12102022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included).The numbers obtained should be printed in a comma-separated sequence on a single line./

In [ ]:
x = 2000
y = 3200

def div_by_7(a,b):
  for i in range(a,b+1):
    if i%7 == 0 and i%5!=0:
      print(i)
    else:
      pass

div_by_7(x,y)


Write a program which can compute the factorial of a given numbers.The results should be printed in a comma-separated sequence on a single line.Suppose the following input is supplied to the program: 8 Then, the output should be:40320

In [ ]:
def fact_num(n):
  if n==0:
    return 1
  else:
    return n*fact_num(n-1)

def ret_fac(n):
  for i in range(1,n+1):
    print(f"Factorial of {i} is {fact_num(i)}")

ret_fac(8)

Factorial of 1 is 1
Factorial of 2 is 2
Factorial of 3 is 6
Factorial of 4 is 24
Factorial of 5 is 120
Factorial of 6 is 720
Factorial of 7 is 5040
Factorial of 8 is 40320


With a given integral number n, write a program to generate a dictionary that contains (i, i x i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary.Suppose the following input is supplied to the program: 8

Then, the output should be:

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [ ]:
def print_dict(n):
  a=[]
  b=[]
  for i in range(1,n+1):
    a.append(i)
    b.append(i**2)
  d=dict(zip(a,b))
  return d

print_dict(8)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [ ]:
def print_dict_1(n):
  a=dict()
  for i in range(1,i+1):
    a[i] = i **2
  return a

print_dict(8)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.Suppose the following input is supplied to the program:

34,67,55,33,12,98
Then, the output should be:

['34', '67', '55', '33', '12', '98']
('34', '67', '55', '33', '12', '98')

In [ ]:
def ret_lijst_tup():
  n = int(input("Enter the no of terms : "))
  a = []
  for i in range(1,n+1):
    b = int(input("Enter the number : "))
    a.append(b)

  print(f"List is : {a}")
  print(f"Tuple id : {tuple(a)}")

ret_lijst_tup()


Enter the no of terms : 5
Enter the number : 34
Enter the number : 67
Enter the number : 55
Enter the number : 33
Enter the number : 12
List is : [34, 67, 55, 33, 12]
Tuple id : (34, 67, 55, 33, 12)


Define a class which has at least two methods:

getString: to get a string from console input
printString: to print the string in upper case.
Also please include simple test function to test the class methods.

In [ ]:
class AB:
  def __init__(self):
    self.s = ""

  def getString(self):
    self.s= input("Enter tyhe string : ") 

  def printString(self):
    print(f"The string is : {self.s.upper()}")

a = AB()
a.getString()
a.printString()

Enter tyhe string : Ajay Sharma
The string is : AJAY SHARMA


Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 _ C _ D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.For example Let us assume the following comma separated input sequence is given to the program:

100,150,180
The output of the program should be:

18,22,24

In [ ]:
import math
def calcu_num():
  C = 50
  H = 30
  n = int(input("Enter the num of terms : "))
  for i in range(1,n+1):
    b = int(input("Enter the number : "))
    q = math.sqrt((2*C*b)/H)
    print(f"Value of {b} is {math.floor(q)}")


calcu_num()
  
  



Enter the num of terms : 3
Enter the number : 100
Value of 100 is 18
Enter the number : 150
Value of 150 is 22
Enter the number : 180
Value of 180 is 24


Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i _ j.*

Note: i=0,1.., X-1; j=0,1,¡­Y-1. Suppose the following inputs are given to the program: 3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [ ]:
x,y = map(int,input().split(','))
lst = []

for i in range(x):
    tmp = []
    for j in range(y):
        tmp.append(i*j)
    lst.append(tmp)

print(lst)

3,5
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world
Then, the output should be:

bag,hello,without,world

In [ ]:
def word_sort():
  n = int(input("Enter the no of terms : "))
  a=[]
  for i in range(1,n+1):
    b = input("Enter the woird : ")
    a.append(b)
  a.sort()
  print(",".join(a))

word_sort()

Enter the no of terms : 4
Enter the woird : without
Enter the woird : hello
Enter the woird : bag
Enter the woird : world
bag,hello,without,world


Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.

Suppose the following input is supplied to the program:

Hello world
Practice makes perfect
Then, the output should be:

HELLO WORLD
PRACTICE MAKES PERFECT

In [ ]:
def get_cap(a):
  return a.upper()

get_cap('Hello world Practice makes perfect')

'HELLO WORLD PRACTICE MAKES PERFECT'

Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again
Then, the output should be:

again and hello makes perfect practice world

In [ ]:
def get_space(a):
  l = a.split(" ")
  for i in l:
    if l.count(i)>1:
      l.remove(i)
  
  print(l)

get_space('hello world and practice makes perfect and hello world again')

['practice', 'makes', 'perfect', 'and', 'hello', 'world', 'again']


Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.

Example:

0100,0011,1010,1001
Then the output should be:

1010

In [ ]:
def bi_to_deci(a):
  return int(a,2)

def dev_vy_5():
  n = int(input("Enter the no of terms : "))
  m=[]
  for i in range(1,n+1):
    b=input("Enter the binary num : ")
    m.append(b)
  for i in m:
    if bi_to_deci(i)%5==0:
      print(f"The binary no is {i} which is divisible by 5")

dev_vy_5()

Enter the no of terms : 3
Enter the binary num : 0100
Enter the binary num : 0011
Enter the binary num : 1010
The binary no is 1010 which is divisible by 5


Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number.The numbers obtained should be printed in a comma-separated sequence on a single line.

In [ ]:
v = []
for i in range(1000,3001):
  s = str(i)
  if (int(s[0])%2 == 0) and (int(s[1])%2 == 0) and (int(s[2])%2 == 0) and (int(s[3])%2 == 0):
    v.append(s)
print(v)
print(len(v))


['2000', '2002', '2004', '2006', '2008', '2020', '2022', '2024', '2026', '2028', '2040', '2042', '2044', '2046', '2048', '2060', '2062', '2064', '2066', '2068', '2080', '2082', '2084', '2086', '2088', '2200', '2202', '2204', '2206', '2208', '2220', '2222', '2224', '2226', '2228', '2240', '2242', '2244', '2246', '2248', '2260', '2262', '2264', '2266', '2268', '2280', '2282', '2284', '2286', '2288', '2400', '2402', '2404', '2406', '2408', '2420', '2422', '2424', '2426', '2428', '2440', '2442', '2444', '2446', '2448', '2460', '2462', '2464', '2466', '2468', '2480', '2482', '2484', '2486', '2488', '2600', '2602', '2604', '2606', '2608', '2620', '2622', '2624', '2626', '2628', '2640', '2642', '2644', '2646', '2648', '2660', '2662', '2664', '2666', '2668', '2680', '2682', '2684', '2686', '2688', '2800', '2802', '2804', '2806', '2808', '2820', '2822', '2824', '2826', '2828', '2840', '2842', '2844', '2846', '2848', '2860', '2862', '2864', '2866', '2868', '2880', '2882', '2884', '2886', '2888']

Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123
Then, the output should be:

LETTERS 10
DIGITS 3

In [ ]:
word = input()
letter, digit = 0,0

for i in word:
    if i.isalpha(): # returns True if alphabet
        letter += 1
    elif i.isnumeric(): # returns True if numeric
        digit += 1
print(f"LETTERS : {letter} and digits : {digit}")

hello world! 123
LETTERS : 10 and digits : 3


Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters.

Suppose the following input is supplied to the program:

Hello world!
Then, the output should be:

UPPER CASE 1
LOWER CASE 9

In [ ]:
word = input()
upper,lower = 0,0

for i in word:
    if 'a'<=i and i<='z' :
        lower+=1
    if 'A'<=i and i<='Z':
        upper+=1

print("UPPER CASE {0}\nLOWER CASE {1}".format(upper,lower))


Hello world!
UPPER CASE 1
LOWER CASE 9


Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a.

Suppose the following input is supplied to the program:

9
Then, the output should be:

11106

In [ ]:
a = input()
print(sum(int(i*a) for i in range(1,5)))

9
11106


In [ ]:
def fi(n):
  if n<0:
    return "Invalid "
  elif n==0:
    return 0
  elif n==1 or n==2:
    return 1
  else:
    return fi(n-1)+fi(n-2)

fi(9)

34

In [ ]:
def is_disarium(n):
  l = len(str(n))
  sum = 0
  for i in range(l):
    sum = sum + int(str(n)[i]) ** (i+1)
  if sum == n:
    return True
  else:
    return False


is_disarium(135)

True

In [1]:
import numpy as np

In [3]:
np.__version__

'1.21.6'

In [4]:
## Creating arrays

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
a[0],a[1]

(1, 2)

In [10]:
for i in a:
  print(i)

1
2
3


In [12]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [14]:
np.linspace(10,100,11)

array([ 10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91., 100.])

In [17]:
## Multi-dimensional arrays


np.array([[2,3],
          [5,6]])

array([[2, 3],
       [5, 6]])

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
## 3*3 idemtity matrix

a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a[2,1] = 20
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1., 20., 20.]])

In [25]:
## random 

np.random.random(3)

array([0.98120025, 0.44861882, 0.07907128])

In [26]:
np.random.randn(3,4)

array([[ 0.72715777, -1.40379975,  1.59461133, -0.23535872],
       [-0.06078121,  0.48694336,  0.35423667,  2.37537095],
       [-0.38892552, -2.31802557,  0.47374719, -0.19168539]])

In [31]:
a.std() , a.mean()

(7.899054483189432, 5.222222222222222)

In [32]:
## Vector operations

u = np.array([2,3,4,5])
u*2

array([ 4,  6,  8, 10])

In [33]:
v = np.array([1, 0, 0, 2])

u + v

array([3, 3, 4, 7])

In [34]:
u * v

array([ 2,  0,  0, 10])

In [37]:
## Multiplication

v.shape[0]

4

In [39]:
def vector_vector_multiplication(u,v):
  assert u.shape[0] == v.shape[0]
  n = u.shape[0]
  r = 0.0
  for i in range(n):
    r = r + u[i] * v[i]
  return r

vector_vector_multiplication(u,v)

12.0

In [40]:
u.dot(v)

12

In [42]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

matrix_vector_multiplication(U,v)


array([14.,  5.,  5.])

DataFrames

In [44]:
import pandas as pd


data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

df = pd.DataFrame(data,columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [45]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

df1 = pd.DataFrame(data)
df1

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [46]:
df[['Make','Model','Year']]

Make     Model  Year
0   Nissan    Stanza  1991
1  Hyundai    Sonata  2017
2    Lotus     Elise  2010
3      GMC    Acadia  2017
4   Nissan  Frontier  2017

In [47]:
df.index = ['a','b','c','d','e']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [52]:
## accessinf only column 


df.iloc[[1,2,4]][['Model','Year']]

Model  Year
b    Sonata  2017
c     Elise  2010
e  Frontier  2017

In [54]:
## Filtering

df[df['Model'] == 'Acadia']

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
d  GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
d       4dr SUV  34450

In [55]:
df[
    (df['Make'] == 'Nissan') & (df['Year'] >= 2015)
]


Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
e  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
e        Pickup  32340

In [56]:
df['Transmission Type'].str.lower()

a       manual
b    automatic
c       manual
d    automatic
e       manual
Name: Transmission Type, dtype: object

In [57]:
'machine learning zoomcamp'.replace(' ', '_')

'machine_learning_zoomcamp'

Grouping

SELECT 
    transmission_type,
    AVG(MSRP)
FROM
    cars
GROUP BY
    transmission_type

In [58]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [62]:

df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64